# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
url: 'https://codes.duniatri.com'
baseurl: ''
title: 'Codes from duniatri'
description: 'Not all about garbage or stuff. It's about learning R and sleepless nights.'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 100
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Duniatri
  url: duniatri.com

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Records
    output: true
    description: "Learning recorder"
    feature_text: |
      It's a train of thought
    feature_image: "https://picsum.photos/2560/600?image=866"
