# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'Journey recorder'
permalink: pretty
logo: "https://lh3.googleusercontent.com/jUWK8WGHU_nBnOoBAdrelwPZSamznE_nGKZWjllkUmwx6tTk8tbpyZe-IMiQVo_poBb0S23ZgS2JuKneNRnFYulSb_G_pk2u-UjRqneJ8HqgfjYuNNjkAWOgQ3fZvXNsDkdyFX5FkN-0-TUdGCIjLszk-WUZu82ofS8xACXSgZJzfi6O3y-XePUY2gpiZftiO_bkc4ulqGcAXL_gnVK6YScdAxhflAjfi2Gg8NWQ_dXprIFvPgfjPJe7_sqHhewDJ2SpOvuEiLKa7FmMfIPAViSkd91P3gsJ6PEkGirhZLmOlSPr1-1JkbWANHrNO_64X6Yl99FCik8XCZcxF0eoBqJqHH7JFANdVyeyYWhm5S2BZtFoFmHO85F2XNlUhDeCmwlM1rlidlL9Bti4M2LokjMTnZi4Ktb7MSMZicEnatkAusBW8xr9vyQR6MhFMk5SAwGcEX3XlLypPBJAl8uFzSO0ww1ki0VuJbLj2nUhehvMOjQTl3_VXsfExUFyT5OuJx0vnwy3eKADQ7lLtaXwkvXRmbZ0nWRNZ9GUAqgxP-yFcY1DJrFC9-I-mFD0FO8FWFVLnb1q1ezaQKWV4JM6Ma0zMkWy2WP0v1LP--PWi-ph8c4hs_N7iiYoOg8zhKG8gR4rZHC1OxbvCEDMkwtJnSILvenaNJ7PJeo3FSf3h2rM1gLedPiB1KzriGj7LK8=w475-h600-no?authuser=0"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Duniatri
  url: duniatri.com

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
